version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Compile and Check Code Style
          command: mvn checkstyle:check
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # Assurez-vous que ce chemin est correct
          token: CODECOV_TOKEN  # Assurez-vous d'ajouter le token Codecov dans les variables d'environnement de CircleCI, si nécessaire
      - run:
          name: Generate javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GIT_HICH_TECH}}
            publish_dir: ./target/site/apidocs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
