version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build